Changes to Game Integration
RaidMax/IW4M-Admin pull request #241
Opened 2022-05-12 21:21 UTC by MrAmos123

+ Freeze (frz) target
+ UnFreeze (ufrz) target
+ PlayerToMe (p2m) target
+ NoClip (nc)
+ UnNoClip (unc)

~ Hide to use God (instead of saving health state)

2022-05-13 13:30 UTC, RaidMax requested changes

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +            response = self LockControlsImpl( event.target );
`self` here is the origin of the command. The action should be executed in the context of the `target`.
This should be `event.target LockControlsImp()`.
Then there is no need to pass the target

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +            response = self UnLockControlsImpl( event.target );
Same comment here

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +        case "UnLockControls":
should just be `UnlockControls`

It's pascal casing and "unlock" is one word

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +        case "UnNoClip":
This should be `NoClipOff` imo

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +            response = self PlayerToMeImpl( event.target );
Because the action is being taking on the target, this should be switched too

`event.target self PlayerToMeImpl( self )`

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    }
This was incorrect as it would just return your name, but making the above proposed changes would fix this.

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    target Hide();
All references to target should be switched to self

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    target thread maps\mp\gametypes\_hud_message::oldNotifyMessage( "ALERT", "You have been frozen!", "compass_waypoint_target", ( 1, 0, 0 ), "ui_mp_nukebomb_timer", 7.5 );
Let's either not use this, or call the the existing hud function. This code is not compatible with other cods and I'd like to use as little as possible

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    self IPrintLnBold( target.name + "\'s controls are locked" );
This should be returned like at the top.

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +UnLockControlsImpl( target )
`UnlockControlsImpl()`

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    target Show();
change to self
this also won't be compatible with other cods

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    self IPrintLnBold( target.name + "\'s controls are unlocked" );
return this text

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +UnNoClipImpl()
`NoClipOffImpl()`

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +PlayerToMeImpl( target )
`PlayerToMe()`

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +        self IPrintLnBold( target.name + " is not alive" );
just return the text as the method context should be the target

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    self SetOrigin( target GetOrigin() );
This would call garbage collisions which is why this command doesn't need to exist imo. Really consider not adding it.

2022-05-13 13:30 UTC, RaidMax commented on GameFiles/IW4x/userraw/scripts/_integration.gsc
> +    target IPrintLnBold( "Moved here " + self.name );
`self IPrintLnBold( "You were moved" );`
Doesn't matter who moved them really.

2022-05-13 13:30 UTC, RaidMax commented on Plugins/ScriptPlugins/GameInterface.js
> +            sendScriptCommand(gameEvent.Owner, 'UnLockControls', gameEvent.Origin, gameEvent.Target, undefined);
UnlockControls

2022-05-13 13:30 UTC, RaidMax commented on Plugins/ScriptPlugins/GameInterface.js
> +            sendScriptCommand(gameEvent.Owner, 'UnNoClip', gameEvent.Origin, gameEvent.Origin, undefined);
NoClipOff

2022-05-13 13:30 UTC, RaidMax commented on Plugins/ScriptPlugins/GameInterface.js
> +        name: 'unnoclip',
I would change to NoClipOff

Clear imo.

2022-05-13 14:40 UTC, MrAmos123 reviewed
Done. :)

2022-05-14 17:55 UTC, xerxes-at commented
Why don't you make NoClip a toggle? It should be rather easy by just saving the status on the player entity for example into player.pers.

2022-05-19 14:49 UTC, MrAmos123 commented
Merged new changes with #242

2022-05-19 14:49 UTC, closed without merging