Fix Game Interface / AC Callbacks + support for T5ZM, T6MP and T6ZM for the Game Interface.
RaidMax/IW4M-Admin pull request #288
Opened 2023-04-09 17:24 UTC by xerxes-at

Fixes the following:

* On IW4, IW5 and T5 it was possible that `level.eventBus.gamename` was being set before `level.eventBus` was initialized as both happened through the init method in 2 different gsc files.

* Paths in `_integration_shared.gsc` pointing to `_integration_base.gsc` did not account for the different paths caused by deploy.bat moving the files to mp only folders for IW5 and T5.

* T6's _customcallbacks.gsc did not compile with the new compiler.

Adds the following:

* Support for T5ZM
    * Remove mp includes from `_integration_base`.
    * Define `GetXuid` as `overrideMethod` as T5ZM doesn't have it.
    * Define `GetPlayerFromClientNum` as `overrideMethod`  since getting all players is slightly different on T5ZM.
 * Support for T6 (MP and ZM)
    * Add `_integration_t6zm_helper.gsc` to support the same hud messages as MP.
    * Add `_integration_t6.gsc`

Other changes:

* Remove precompiled `_customcallbacks.gsc` for T6 as it can now load uncompiled GSC and the compiler used by Pluto is much better than the old one.
* Changes to deploy.bat to support the other changes.

2023-04-09 17:29 UTC, diamante0018 reviewed
You should removed the compiled T6 plugin. There should not be a reason to encourage loading scripts that way.

2023-04-09 17:31 UTC, diamante0018 requested changes
You should removed the compiled T6 plugin. There should not be a reason t encourage loading scripts that way.

2023-04-09 17:31 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_iw4x.gsc
> +_GetXUID()
No this is wrong. See how `ISTestClient` function is called in the same file.
You need to use the `call` keyword.

2023-04-09 17:33 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_iw5.gsc
> +_GetXUID()
Same as iw4 engine

2023-04-09 17:42 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_t6.gsc
> +    scripts\_integration_base::LogWarning( "NoClip is not supported on T6!" );
Noclip should be a built-in on t6 iirc

2023-04-09 17:42 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_t6.gsc
> +        {
Use istestclient as it is a built-in

2023-04-09 17:42 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_t5zm.gsc
> +        {
Same

2023-04-09 17:42 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_t5.gsc
> +{
On the 3arc engine you do not need the call keyword to call a built-in by reference but it should be attempted anyway

2023-04-10 12:57 UTC, diamante0018 approved these changes
Most of my comments can be discarded.
At the end because of the 3arc engine the call keyword can't be used so it forces us to use wrapper function.
I confirmed noclip is not supported on t5/t6 yet.
but I could be added to iw5 if it's not already done.

2023-04-10 14:27 UTC, RaidMax commented on GameFiles/GameInterface/_integration_base.gsc
> +    level.commonFunctions.GetPlayerFromClientNum = "GetPlayerFromClientNum";
nit: use camelCase for functionName
`level.commonFunctions.getPlayerFromClientNum`

2023-04-10 14:32 UTC, RaidMax commented on GameFiles/GameInterface/_integration_base.gsc
> +    guid = self [[level.overrideMethods[level.commonFunctions.getXuid]]]();
So after thinking about this, I think we should move the `GenerateJoinTeamString` into the _integration_shared.gsc 
I added this in here before I created the shared functionality file.
Philosophically the _integration_base,gsc should really only be responsible for facilitating the game interface data transfer/notifications. No direct game interaction or action on game events.

2023-04-10 14:38 UTC, RaidMax commented
What's the reason for defining an entirely new set of methods for T5ZM? Could we not check a dvar to see if it's zm vs mp and then register the GetXuid and GetPlayerFromClientNum respectively?

2023-04-26 14:02 UTC, diamante0018 commented on GameFiles/GameInterface/_integration_t6.gsc
> +    _SetDvarIfUninitialized("sv_iw4madmin_autobalance",0);
minor complaint here but could you leave a space after the comma and also space out the parameters like in the rest of the file?

2023-04-26 14:02 UTC, xerxes-at commented
Your guess regarding t5zm is dead on, unlike on t6 it will complain about any and all mp scripts.

2023-05-29 01:15 UTC, RaidMax approved these changes

2023-05-29 01:15 UTC, merged